name := "test-sbt-project-switcher"
version := "0.1.0"

enablePlugins(ProjectSwitcher)

lazy val root = project in file(".")
lazy val projectA = project in file("a")
lazy val projectB = project in file("b")
lazy val projectC = project in file("c")
lazy val projectD = project in file("d")
lazy val projectE = project in file("e")
lazy val projectF = project in file("f")
lazy val projectG = project in file("g")
lazy val projectH = project in file("h")
lazy val projectI = project in file("i")
lazy val projectJ = project in file("j")
lazy val projectK = project in file("k")
lazy val projectL = project in file("l")
lazy val projectM = project in file("m")
lazy val projectN = project in file("n")
lazy val projectO = project in file("o")
lazy val projectP = project in file("p")
lazy val projectQ = project in file("q")
lazy val projectR = project in file("r")
lazy val projectS = project in file("s")
lazy val projectT = project in file("t")
lazy val projectU = project in file("u")
lazy val projectV = project in file("v")
lazy val projectW = project in file("w")
lazy val projectX = project in file("x")
lazy val projectY = project in file("y")
lazy val projectZ = project in file("z")